Experiment: theanolm-morph-42k/expt2-sampled
Job ID: 55034171
Task ID: 
Host: gpu36.int.triton.aalto.fi
Start date: Sun Aug  9 11:18:22 EEST 2020
Work directory: /scratch/work/moisioa3/conv_lm/experiments/theanolm-morph-42k/expt2-sampled
Temporary directory: /tmp/55034171

Currently Loaded Modules:
  1) srilm/default      3) cuda/10.0.130
  2) anaconda3/latest   4) cudnn/7.4.2-cuda

 

floatX=float32,device=cuda0,base_compiledir=/tmp/theano,exception_verbosity=high,openmp=False
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 7402 on context None
Mapped name None to device cuda0: Tesla V100-PCIE-32GB (0000:18:00.0)
TheanoLM 1.3.2
Theano 1.0.4
pygpu 0.7.6
==
+ srun --gres=gpu:1 theanolm train /scratch/work/moisioa3/conv_lm/experiments/theanolm-morph-42k/expt2-sampled/nnlm.h5 --training-set /scratch/work/moisioa3/conv_lm/data/segmented/42k/dsp.txt /scratch/work/moisioa3/conv_lm/data/segmented/42k/web.txt --validation-file /scratch/work/moisioa3/conv_lm/data/segmented/42k/devel.txt --sequence-length 25 --batch-size 24 --optimization-method adagrad --stopping-criterion annealing-count --cost cross-entropy --learning-rate 0.1 --gradient-decay-rate 0.9 --numerical-stability-term 1e-6 --num-noise-samples 500 --noise-dampening 0.5 --noise-sharing batch --validation-frequency 5 --patience 2 --max-epochs 25 --min-epochs 1 --random-seed 1 --log-level debug --log-interval 1000 --gradient-normalization 5 --architecture /scratch/work/moisioa3/conv_lm/configs/word+proj500+lstm1500+htanh1500x4+dropout0.2+softmax.arch --sampling 1 0.2
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/theano/gpuarray/dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 7402 on context None
Mapped name None to device cuda0: Tesla V100-PCIE-32GB (0000:18:00.0)
2020-08-09 11:18:32,299 exception_handler: An unexpected OSError exception occurred: Unable to create file (unable to open file)
Traceback will be written to debug log (enable with --log-level debug).
2020-08-09 11:18:32,299 exception_handler: Traceback:
2020-08-09 11:18:32,334 exception_handler: File "/scratch/work/groszt1/envs/theanoLM/bin/theanolm", line 4, in <module>
    __import__('pkg_resources').run_script('TheanoLM==1.3.2', 'theanolm')
2020-08-09 11:18:32,334 exception_handler: File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
2020-08-09 11:18:32,334 exception_handler: File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
2020-08-09 11:18:32,334 exception_handler: File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/TheanoLM-1.3.2-py3.7.egg/EGG-INFO/scripts/theanolm", line 147, in <module>
    main()
2020-08-09 11:18:32,334 exception_handler: File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/TheanoLM-1.3.2-py3.7.egg/EGG-INFO/scripts/theanolm", line 88, in main
    args.command_function(args)
2020-08-09 11:18:32,335 exception_handler: File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/TheanoLM-1.3.2-py3.7.egg/theanolm/commands/train.py", line 355, in train
    with h5py.File(args.model_path, 'a', driver='core') as state:
2020-08-09 11:18:32,335 exception_handler: File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/h5py-2.9.0-py3.7-linux-x86_64.egg/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
2020-08-09 11:18:32,335 exception_handler: File "/scratch/work/groszt1/envs/theanoLM/lib/python3.7/site-packages/h5py-2.9.0-py3.7-linux-x86_64.egg/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
2020-08-09 11:18:32,335 exception_handler: File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
2020-08-09 11:18:32,335 exception_handler: File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
2020-08-09 11:18:32,335 exception_handler: File "h5py/h5f.pyx", line 105, in h5py.h5f.create
srun: error: gpu36: task 0: Exited with exit code 2
srun: Terminating job step 55034171.0
